---
- name: configure /etc/portage/package.use/*
  copy:
    src: "package.use/{{ item }}"
    dest: "/etc/portage/package.use/{{ item }}"
  with_items:
    - ibus-skk

- name: configure /etc/portage/package.accept_keywords/*
  copy:
    src: "package.accept_keywords/{{ item }}"
    dest: "/etc/portage/package.accept_keywords/{{ item }}"
  with_items:
    - ricty

- name: configure /etc/portage/package.license/*
  copy:
    src: "package.license/{{ item }}"
    dest: "/etc/portage/package.license/{{ item }}"
  with_items:
    - skk-jisyo

- name: install fonts, cursor, and IME
  portage:
    package: "{{ item }}"
    state: present
  with_items:
    - ibus-skk
    - ricty
    - takao-fonts
    - vanilla-dmz-xcursors
