---
- hosts: localhost
  connection: local
  become: true
  vars:
    portage:
      use: ''
      cpu_flags_x86: 'aes avx mmx mmxext pclmul popcnt sse sse2 sse3 sse4_1 sse4_2 ssse3'
      linguas: 'ja'
      makeopts: '-j3'
    iptables: {}
    ip6tables: {}
    openssh:
      xforwarding: true
    certbot:
      domains:
        - www.wacky612.net
  roles:
    - glibc
    - systemd
    - openssh
    - cli
    - prince
    - certbot
  post_tasks:
    - import_role: 
        name: iptables
