---
- hosts: localhost
  connection: local
  become: true
  vars:
    portage:
      use: ''
      cpu_flags_x86: 'aes avx mmx mmxext pclmul popcnt sse sse2 sse3 sse4_1 sse4_2 ssse3'
      linguas: 'ja'
      makeopts: '-j3'
    iptables: {}
    ip6tables: {
      'filter': {
        'MISC': { 'rules': [ '-p ipencap -j ACCEPT' ] }
      }
    }
    openssh:
      xforwarding: true
  roles:
    - systemd
    - openssh
    - cli
    - prince
  post_tasks:
    - import_role: 
        name: iptables
