---
- hosts: localhost
  connection: local
  become: true
  vars:
    portage:
      use: 'pulseaudio X wayland'
      cpu_flags_x86: 'aes avx avx2 f16c fma3 mmx mmxext pclmul popcnt sse sse2 sse3 sse4_1 sse4_2 ssse3'
      linguas: 'ja'
      makeopts: '-j5'
    iptables: {}
    ip6tables: {}
    openssh:
      xforwarding: false
    xorg:
      video_cards: 'intel i965'
  roles:
    - glibc
    - systemd
    - openssh
    - cli
    - atftp
    - samba
    - xorg-server
    - greetd
    - qtile
    - sway
    - gui
    - prince
  post_tasks:
    - import_role:
        name: iptables
