---
- hosts: localhost
  connection: local
  become: true
  vars:
    portage:
      use: 'bindist pulseaudio'
      cpu_flags_x86: 'aes avx avx2 f16c fma3 mmx mmxext pclmul popcnt sse sse2 sse3 sse4_1 sse4_2 ssse3'
      linguas: 'ja'
      makeopts: '-j5'
    iptables: {}
    xorg:
      video_cards: 'intel i965'
  roles:
    - systemd
    - openssh
    - cli
    - samba
    - xorg
    - lightdm
    - xmonad
    - gui
    - prince
  post_tasks:
    - import_role: 
        name: iptables
