---
- name: configure /etc/portage/package.use/*
  copy:
    src: "package.use/{{ item }}"
    dest: "/etc/portage/package.use/{{ item }}"
  with_items:
    - samba

- name: install samba
  portage:
    package: samba
    state: present

- name: enable samba
  systemd:
    name: "{{ item }}"
    enabled: yes
  with_items:
    - smb
    - nmb

- name: install /etc/samba/smb.conf
  copy:
    src: smb.conf
    dest: /etc/samba/smb.conf
  notify:
    - restart samba

- name: load iptables config for samba
  set_fact:
    iptables: "{{ iptables | deepmerge({
      'TCP': {
        'rules': [
          '-s 192.168.0.0/16 -p tcp --dport 137:139 -j ACCEPT',
          '-s 172.16.0.0/12  -p tcp --dport 137:139 -j ACCEPT',
          '-s 10.0.0.0/8     -p tcp --dport 137:139 -j ACCEPT',
          '-s 192.168.0.0/16 -p tcp --dport 445 -j ACCEPT',
          '-s 172.16.0.0/12  -p tcp --dport 445 -j ACCEPT',
          '-s 10.0.0.0/8     -p tcp --dport 445 -j ACCEPT'
        ]
      },
      'UDP': {
        'rules': [
          '-s 192.168.0.0/16 -p udp --dport 137:139 -j ACCEPT',
          '-s 172.16.0.0/12  -p udp --dport 137:139 -j ACCEPT',
          '-s 10.0.0.0/8     -p udp --dport 137:139 -j ACCEPT',
          '-s 192.168.0.0/16 -p udp --dport 445 -j ACCEPT',
          '-s 172.16.0.0/12  -p udp --dport 445 -j ACCEPT',
          '-s 10.0.0.0/8     -p udp --dport 445 -j ACCEPT'
        ]
      }
    }) }}"
    ip6tables: "{{ ip6tables | deepmerge({
      'TCP': {
        'rules': [
          '-s fc00::/7 -p tcp --dport 137:139 -j ACCEPT',
          '-s fc00::/7 -p tcp --dport 445 -j ACCEPT'
        ]
      },
      'UDP': {
        'rules': [
          '-s fc00::/7 -p udp --dport 137:139 -j ACCEPT',
          '-s fc00::/7 -p udp --dport 445 -j ACCEPT'
        ]
      }
    }) }}"
