---
- name: configure /etc/portage/package.use/*
  copy:
    src: "package.use/{{ item }}"
    dest: "/etc/portage/package.use/{{ item }}"
  with_items:
    - qtile
    - dunst

- name: install qtile and some packages
  portage:
    package: "{{ item }}"
    state: present
  with_items:
    - qtile
    - dunst
    - psutil
    - xset
