---
- name: enable iptables/ip6tables
  systemd:
    name: "{{ item }}-restore"
    enabled: yes
  with_items:
    - iptables
    - ip6tables

- name: load iptables config
  set_fact:
    iptables: "{{ iptables | deepmerge({
      'filter': {
        'INPUT': {
          'policy': 'DROP',
          'rules': [
            '-m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT',
            '-i lo -j ACCEPT',
            '-m conntrack --ctstate INVALID -j DROP',
            '-p icmp -m icmp --icmp-type 8 -m conntrack --ctstate NEW -j ACCEPT',
            '-p udp -m conntrack --ctstate NEW -j UDP',
            '-p tcp --tcp-flags FIN,SYN,RST,ACK SYN -m conntrack --ctstate NEW -j TCP',
            '-j MISC',
            '-p udp -j REJECT --reject-with icmp-port-unreachable',
            '-p tcp -j REJECT --reject-with tcp-reset',
            '-j REJECT --reject-with icmp-proto-unreachable'
          ]
        },
        'OUTPUT': { 'policy': 'ACCEPT', 'rules': [] },
        'FORWARD': { 'policy': 'DROP', 'rules': [] },
        'TCP': { 'policy': '-', 'rules': [] },
        'UDP': { 'policy': '-', 'rules': [] },
        'MISC': { 'policy': '-', 'rules': [] }
      }
    }) }}"
    ip6tables: "{{ ip6tables | deepmerge({
      'filter': {
        'INPUT': {
          'policy': 'DROP',
          'rules': [
            '-m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT',
            '-i lo -j ACCEPT',
            '-m conntrack --ctstate INVALID -j DROP',
            '-p icmpv6 -j ICMP',
            '-p udp -m conntrack --ctstate NEW -j UDP',
            '-p tcp --tcp-flags FIN,SYN,RST,ACK SYN -m conntrack --ctstate NEW -j TCP',
            '-j MISC',
            '-p udp -j REJECT --reject-with icmp6-port-unreachable',
            '-p tcp -j REJECT --reject-with tcp-reset',
            '-j REJECT --reject-with icmp6-adm-prohibited'
          ]
        },
        'OUTPUT': { 'policy': 'ACCEPT', 'rules': [] },
        'FORWARD': { 'policy': 'DROP', 'rules': [] },
        'TCP': { 'policy': '-', 'rules': [] },
        'UDP': { 'policy': '-', 'rules': [] },
        'ICMP': {
          'policy': '-',
          'rules': [
            '-p icmpv6 --icmpv6-type 1 -j ACCEPT',
            '-p icmpv6 --icmpv6-type 2 -j ACCEPT',
            '-p icmpv6 --icmpv6-type 3 -j ACCEPT',
            '-p icmpv6 --icmpv6-type 4 -j ACCEPT',
            '-p icmpv6 --icmpv6-type 128 -j ACCEPT',
            '-p icmpv6 --icmpv6-type 129 -j ACCEPT',
            '-p icmpv6 --icmpv6-type 133 -m hl --hl-eq 255 -j ACCEPT',
            '-p icmpv6 --icmpv6-type 134 -m hl --hl-eq 255 -j ACCEPT',
            '-p icmpv6 --icmpv6-type 135 -m hl --hl-eq 255 -j ACCEPT',
            '-p icmpv6 --icmpv6-type 136 -m hl --hl-eq 255 -j ACCEPT',
            '-p icmpv6 --icmpv6-type 141 -m hl --hl-eq 255 -j ACCEPT',
            '-p icmpv6 --icmpv6-type 142 -m hl --hl-eq 255 -j ACCEPT',
            '-p icmpv6 --icmpv6-type 130 -s fe80::/10 -j ACCEPT',
            '-p icmpv6 --icmpv6-type 131 -s fe80::/10 -j ACCEPT',
            '-p icmpv6 --icmpv6-type 132 -s fe80::/10 -j ACCEPT',
            '-p icmpv6 --icmpv6-type 143 -s fe80::/10 -j ACCEPT',
            '-p icmpv6 --icmpv6-type 148 -m hl --hl-eq 255 -j ACCEPT',
            '-p icmpv6 --icmpv6-type 149 -m hl --hl-eq 255 -j ACCEPT',
            '-p icmpv6 --icmpv6-type 151 -s fe80::/10 -m hl --hl-eq 1 -j ACCEPT',
            '-p icmpv6 --icmpv6-type 152 -s fe80::/10 -m hl --hl-eq 1 -j ACCEPT',
            '-p icmpv6 --icmpv6-type 153 -s fe80::/10 -m hl --hl-eq 1 -j ACCEPT'
          ]
        },
        'MISC': { 'policy': '-', 'rules': [] }
      }
    }) }}"

- name: install /var/lib/iptables/rules-save
  template:
    src: iptables/rules-save.j2
    dest: /var/lib/iptables/rules-save
  notify: reload iptables

- name: install /var/lib/ip6tables/rules-save
  template:
    src: ip6tables/rules-save.j2
    dest: /var/lib/ip6tables/rules-save
  notify: reload ip6tables
