---
- name: enable iptables/ip6tables
  systemd:
    name: "{{ item }}-restore"
    enabled: yes
  with_items:
    - iptables
    - ip6tables

- name: load iptables config
  set_fact:
    iptables: "{{ iptables | deepmerge({
      'INPUT': {
        'policy': 'DROP',
        'rules': [
          '-m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT',
          '-i lo -j ACCEPT',
          '-m conntrack --ctstate INVALID -j DROP',
          '-p icmp -m icmp --icmp-type 8 -m conntrack --ctstate NEW -j ACCEPT',
          '-p udp -m conntrack --ctstate NEW -j UDP',
          '-p tcp --tcp-flags FIN,SYN,RST,ACK SYN -m conntrack --ctstate NEW -j TCP',
          '-p udp -j REJECT --reject-with icmp-port-unreachable',
          '-p tcp -j REJECT --reject-with tcp-reset',
          '-j REJECT --reject-with icmp-proto-unreachable'
        ]
      },
      'OUTPUT': { 'policy': 'ACCEPT', 'rules': [] },
      'FORWARD': { 'policy': 'DROP', 'rules': [] },
      'TCP': { 'policy': '-', 'rules': [] },
      'UDP': { 'policy': '-', 'rules': [] }
    }) }}"
    ip6tables: "{{ ip6tables | deepmerge({
      'INPUT': {
        'policy': 'DROP',
        'rules': [
          '-m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT',
          '-i lo -j ACCEPT',
          '-m conntrack --ctstate INVALID -j DROP',
          '-p ipv6-icmp --icmpv6-type 128 -m conntrack --ctstate NEW -j ACCEPT',
          '-s fe80::/10 -p ipv6-icmp -j ACCEPT',
          '-p udp -m conntrack --ctstate NEW -j UDP',
          '-p tcp --tcp-flags FIN,SYN,RST,ACK SYN -m conntrack --ctstate NEW -j TCP',
          '-p udp -j REJECT --reject-with icmp6-port-unreachable',
          '-p tcp -j REJECT --reject-with tcp-reset',
          '-j REJECT --reject-with icmp6-adm-prohibited'
        ]
      },
      'OUTPUT': { 'policy': 'ACCEPT', 'rules': [] },
      'FORWARD': { 'policy': 'DROP', 'rules': [] },
      'TCP': { 'policy': '-', 'rules': [] },
      'UDP': { 'policy': '-', 'rules': [] }
    }) }}"

- name: install /var/lib/iptables/rules-save
  template:
    src: iptables/rules-save.j2
    dest: /var/lib/iptables/rules-save
  notify: reload iptables

- name: install /var/lib/ip6tables/rules-save
  template:
    src: ip6tables/rules-save.j2
    dest: /var/lib/ip6tables/rules-save
  notify: reload ip6tables
