---
- name: configure /etc/portage/package.use/*
  copy:
    src: "package.use/{{ item }}"
    dest: "/etc/portage/package.use/{{ item }}"
  with_items:
    - mpv
    - pavucontrol
    - rxvt-unicode
    - vivaldi
    - zathura-pdf-mupdf

- name: configure /etc/portage/package.license/*
  copy:
    src: "package.license/{{ item }}"
    dest: "/etc/portage/package.license/{{ item }}"
  with_items:
    - vivaldi

- name: install gui applications
  portage:
    package: "{{ item }}"
    state: present
  with_items:
    - mpv
    - pavucontrol
    - urxvt-font-size
    - urxvt-perls
    - youtube-dl
    - zathura-pdf-mupdf

- name: install vivaldi
  portage:
    package: "{{ item }}"
    state: present
  with_items:
    - vivaldi
    - libxkbcommon
