---
- name: configure /etc/portage/package.use/*
  copy:
    src: "package.use/{{ item }}"
    dest: "/etc/portage/package.use/{{ item }}"
  with_items:
    - chromium
    - mpv
    - rxvt-unicode
    - zathura-pdf-mupdf

- name: configure /etc/portage/package.keywords/*
  copy:
    src: "package.keywords/{{ item }}"
    dest: "/etc/portage/package.keywords/{{ item }}"
  with_items:
    - lastpass-cli
    - ricty

- name: install gui applications
  portage:
    package: "{{ item }}"
    state: present
  with_items:
    - chromium
    - ibus-skk
    - lastpass-cli
    - mpv
    - ricty
    - takao-fonts
    - urxvt-font-size
    - urxvt-perls
    - vanilla-dmz-xcursors
    - zathura-pdf-mupdf
