---
- name: configure /etc/portage/package.use/*
  copy:
    src: "package.use/{{ item }}"
    dest: "/etc/portage/package.use/{{ item }}"
  with_items:
    - chromium
    - mpv
    - rxvt-unicode
    - zathura-pdf-mupdf

- name: install gui applications
  portage:
    package: "{{ item }}"
    state: present
  with_items:
    - chromium
    - mpv
    - urxvt-font-size
    - urxvt-perls
    - zathura-pdf-mupdf
