---
- name: configure /etc/portage/package.use/openssh
  copy:
    src: package.use/openssh
    dest: /etc/portage/package.use/openssh
  when: openssh.xforwarding

- name: install openssh
  portage:
    package: openssh
    state: present

- name: enable sshd
  systemd:
    name: sshd
    enabled: yes

- name: modify /etc/ssh/sshd_config
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?{{ item.key }}"
    line: "{{ item.key }} {{ item.value }}"
  with_items:
    - { key: PermitRootLogin, value: 'no' }
    - { key: PasswordAuthentication, value: 'no' }
    - { key: ChallengeResponseAuthentication, value: 'no' }
  notify:
    - restart sshd

- name: set X11Forwarding to yes
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?{{ item.key }}"
    line: "{{ item.key }} {{ item.value }}"
  with_items:
    - { key: X11Forwarding, value: 'yes' }
  when: openssh.xforwarding
  notify:
    - restart sshd

- name: load iptables config for openssh
  set_fact:
    iptables: "{{ iptables | deepmerge({
      'TCP': { 'rules': [ '-p tcp --dport 22 -j ACCEPT' ] },
    }) }}"
    ip6tables: "{{ ip6tables | deepmerge({
      'TCP': { 'rules': [ '-p tcp --dport 22 -j ACCEPT' ] },
    }) }}"
