---
- name: create portage directorys
  file:
    path: "/etc/portage/{{ item }}"
    mode: 0755
    state: directory
  with_items:
    - package.use
    - package.accept_keywords
    - package.license
    - repos.conf

- name: create local portage directory
  file:
    path: "/var/db/repos/{{ item }}"
    mode: 0755
    state: directory
  with_items:
    - local
    - local/metadata
    - local/profiles

- name: modify /etc/portage/make.conf
  lineinfile:
    path: /etc/portage/make.conf
    regexp: "^#?{{ item.key }}"
    line: "{{ item.key }}=\"{{ item.value }}\""
  with_items:
    - { key: COMMON_FLAGS, value: '-march=native -O2 -pipe' }
    - { key: USE, value: "{{ portage.use }}" }
    - { key: CPU_FLAGS_X86, value: "{{ portage.cpu_flags_x86 }}" }
    - { key: LINGUAS, value: "{{ portage.linguas }}" }
    - { key: MAKEOPTS, value: "{{ portage.makeopts }}" }
    - { key: GENTOO_MIRRORS, value: 'http://ftp.iij.ad.jp/pub/linux/gentoo' }

- name: install /etc/portage/repos.conf/local.conf
  copy:
    src: local.conf
    dest: /etc/portage/repos.conf/local.conf

- name: install /var/db/repos/local/profiles/repo_name
  copy:
    src: "{{ item.src }}"
    dest: "/var/db/repos/local/{{ item.dest }}"
  with_items:
    - { src: repo_name, dest: profiles/ }
    - { src: layout.conf, dest: metadata/ }

- name: install eix
  portage:
    package: eix
    state: present
