---
- name: create app-text/prince directorys
  file:
    path: "/var/db/repos/local/{{ item }}"
    mode: 0755
    state: directory
  with_items:
    - app-text
    - app-text/prince
    - app-text/prince/files

- name: install app-text/prince/*
  copy:
    src: "{{ item }}"
    dest: "/var/db/repos/local/app-text/prince/{{ item }}"
  with_items:
    - Manifest
    - prince-6.0_p8.ebuild
    - files/prince-6.0-destdir.patch

- name: configure /etc/portage/package.license/*
  copy:
    src: "package.license/{{ item }}"
    dest: "/etc/portage/package.license/{{ item }}"
  with_items:
    - prince

- name: install prince
  portage:
    package: prince
    state: present
