---
- name: configure /etc/portage/package.use/*
  copy:
    src: "package.use/{{ item }}"
    dest: "/etc/portage/package.use/{{ item }}"
  with_items:
    - lightdm

- name: configure /etc/portage/package.accept_keywords/*
  copy:
    src: "package.accept_keywords/{{ item }}"
    dest: "/etc/portage/package.accept_keywords/{{ item }}"
  with_items:
    - lightdm

- name: install lightdm
  portage:
    package: light-locker
    state: present

- name: enable lightdm
  systemd:
    name: lightdm
    enabled: yes
