---
- name: create gui-apps/swaylock-effects directorys
  file:
    path: "/var/db/repos/local/{{ item }}"
    mode: 0755
    state: directory
  with_items:
    - gui-apps
    - gui-apps/swaylock-effects

- name: install gui-apps/swaylock-effects/*
  copy:
    src: "{{ item }}"
    dest: "/var/db/repos/local/gui-apps/swaylock-effects/{{ item }}"
  with_items:
    - Manifest
    - swaylock-effects-9999.ebuild

- name: configure /etc/portage/package.accept_keywords/*
  copy:
    src: "package.accept_keywords/{{ item }}"
    dest: "/etc/portage/package.accept_keywords/{{ item }}"
  with_items:
    - swaylock-effects

- name: install swaylock-effects
  portage:
    package: swaylock-effects
    state: present
