---
- name: modify /etc/portage/make.conf
  lineinfile:
    path: /etc/portage/make.conf
    regexp: "^#?{{ item.key }}"
    line: "{{ item.key }}=\"{{ item.value }}\""
  with_items:
    - { key: VIDEO_CARDS, value: "{{ xorg.video_cards }}" }

- name: install linux-firmware if VIDEO_CARDS include intel
  portage:
    package: linux-firmware
    state: present
  when: xorg.video_cards is match('intel')

- name: configure /etc/portage/package.use/*
  copy:
    src: "package.use/{{ item }}"
    dest: "/etc/portage/package.use/{{ item }}"
  with_items:
    - xorg-server

- name: install xorg-server
  portage:
    package: xorg-server
    state: present

- name: install xorg config
  copy:
    src: 00-keyboard.conf
    dest: /etc/X11/xorg.conf.d/
