---
- name: configure /etc/portage/package.use/*
  copy:
    src: "package.use/{{ item }}"
    dest: "/etc/portage/package.use/{{ item }}"
  with_items:
    - xmobar
    - dunst
    - pavucontrol

- name: configure /etc/portage/package.accept_keywords/*
  copy:
    src: "package.accept_keywords/{{ item }}"
    dest: "/etc/portage/package.accept_keywords/{{ item }}"
  with_items:
    - xmonad
    - xmobar
    - haskell

- name: install xmonad and some packages
  portage:
    package: "{{ item }}"
    state: present
  with_items:
    - xmonad-contrib
    - xmobar
    - dmenu
    - dunst
    - pavucontrol
    - xset
