---
- name: configure /etc/portage/package.use/*
  copy:
    src: "package.use/{{ item }}"
    dest: "/etc/portage/package.use/{{ item }}"
  with_items:
    - xmobar
    - dunst
    - pavucontrol
    - pavumeter
    - trayer

- name: configure /etc/portage/package.accept_keywords/*
  copy:
    src: "package.accept_keywords/{{ item }}"
    dest: "/etc/portage/package.accept_keywords/{{ item }}"
  with_items:
    - xmonad
    - pasystray

- name: install xmonad and some packages
  portage:
    package: "{{ item }}"
    state: present
  with_items:
    - xmonad-contrib
    - xmobar
    - dmenu
    - dunst
    - pasystray
    - pavucontrol
    - pavumeter
    - trayer
    - xset

- name: install xmonad.desktop
  copy:
    src: xmonad.desktop
    dest: /usr/share/xsessions/xmonad.desktop
