---
- name: configure /etc/portage/package.use/*
  copy:
    src: "package.use/{{ item }}"
    dest: "/etc/portage/package.use/{{ item }}"
  with_items:
    - feh
    - iputils

- name: install cli applications
  portage:
    package: "{{ item }}"
    state: present
  with_items:
    - bind-tools
    - bundler
    - convmv
    - direnv
    - emacs
    - feh
    - gentoo-zsh-completions
    - nano
    - nkf
    - source-highlight
    - tig
    - tmux
